### PR TITLE
0.9: Create `remote` accessor

### PR DESCRIPTION
**Pull request by boardfish**
Now we're using Active Record Types to serialize to and deserialize from the ID to the record. This should start to simplify things in a major way.

It should be possible to have multiple remote resources linked to one object, and with any luck, it should be as simple as using the Active Record Types API like:

```ruby
# Assuming your model has:
# github_user | '51171867'
# github_repo | '221279228'
attribute :github_user, RemoteRecord::GitHub::User::Type[config].new
attribute :github_repo, RemoteRecord::GitHub::Repository::Type[config].new
```

Remote Record classes now have types that you can serialize to an instance of the Remote Record class.

The `remote_record` DSL method sets up these Active Record types as above, and creates an accessor for your ID fields at `remote`. The default is still `remote_resource_id`, but it can be changed. You can also use `remote` to access the other fields by passing their names as a parameter, so you could use `remote(:github_user)` or `remote(:github_repo)` for the above.

---

~~This feels like a big shift. I'm going to break the work down, but the amount this changes means it's effectively a full rewrite of what we've got already.~~

It's starting to feel like a nice refactor. `Config` is becoming much less responsible for the link between a remote record class and a remote reference.

---

TODO:

- [x] Reintroduce compatibility with:
  - [x] configs #44 
  - [x] fetching control #45 
  - [x] transforms #44 
  - [x] batch fetching
    - [x] ActiveRecord #46 
    - [x] overriding `all` #47 
    - [x] querying the API first #47 
    - [ ] ~~some sort of option not to scope the results of a `Collection` to a relation (find or initialize)~~ later?
- [x] an update to the DSL to allow you to change the field name
- [x] update header image`
- [x] Update docs and comments - to do once other PRs are reviewed
- [x] fix: unclear that `remote_record` overrides `#remote`. What should the behavior be?

### CODE REVIEW

**Comment by boardfish** [comment]
I still need to tackle that last couple of problems and update the documentation for them before this is fully ready. As it stands, it removes some features from Remote Record that we're actively using.

**Comment by boardfish** [comment]
`rescue_from` can't really work in the same way now. Previously, Remote Record's actions are scoped to the reference and not the remote record class. However, that changes in this PR. So it's not possible to have a `rescue_from` defined on the reference.

If folks drop in Remote Record classes from other gems, they'll have to monkey-patch them to set a `rescue_from` hook, e.g.:

```ruby
# Gemfile
gem 'remote_record'
gem 'remote_record-github'`
```

```ruby
# app/lib/remote_record/github/user.rb

module RemoteRecord
  module GitHub
    class User
      rescue_from Octokit::Unauthorized do |exception|
        Honeybadger.notify(exception)
      end
    end
  end
end
```

That feels a bit less than ideal.

**Review by johndbritton — APPROVED** [review]

**Comment by boardfish** [comment]
We talked about:

- making the `remote` scope and method name configurable
- Raising an error if it clashes with something else
- Putting the `Type` class definition elsewhere if possible

**Comment by boardfish** [comment]
Running into a problem when bringing this back into our app - authorization used to be relative to the remote reference, but now there's no link. I need to work around this somehow.

I'm thinking we add an `authorization_parent` option to config, and when `authorization` is called, use that.

**Comment by boardfish** [comment]
I think this is ready for review now as it's proven to be working within our own app.

Coming back to:

> making the remote scope and method name configurable
> Raising an error if it clashes with something else

Are these a requirement for this PR?

**Pull request merged**
